# Welcome to Serverless!
#
# For full config options, check out the Alibaba Cloud Function Compute
# plugin docs:
#    https://github.com/aliyun/serverless-aliyun-function-compute
#
# For documentation on Alibaba Cloud Function Compute itself:
#    https://serverless.aliyun.com

# Update the service name below with your own service name

service: aliyun-nodejs

provider:
  name: aliyun
  runtime: nodejs16.x
  credentials: ~/.aliyuncli/credentials # path must be absolute
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-aliyun-function-compute
  - serverless-offline

package:
  exclude:
    - package-lock.json
    - .gitignore
    - .git/**

functions:
  createTask:
    handler: tasks.create
    events:
      - http:
          path: tasks
          method: post
  # checkStatus:
  #   handler: tasks.checkStatus
  #   events:
  #     - http:
  #         path: tasks/{id}/status
  #         method: get
  # getResult:
  #   handler: tasks.getResult
  #   events:
  #     - http:
  #         path: tasks/{id}/result
  #         method: get
  getAllModels:
    handler: models.getALL
    events:
      - http:
          path: models
          method: get
  getModel:
    handler: models.getOne
    events:
      - http:
          path: models/{id}
          method: get