// source: requests.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ModelTask');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.StableDiffusionParameter');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ModelTask = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ModelTask, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ModelTask.displayName = 'proto.ModelTask';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ModelTask.prototype.toObject = function(opt_includeInstance) {
  return proto.ModelTask.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ModelTask} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ModelTask.toObject = function(includeInstance, msg) {
  var f, obj = {
    stablediffusion: (f = msg.getStablediffusion()) && proto.StableDiffusionParameter.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ModelTask}
 */
proto.ModelTask.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ModelTask;
  return proto.ModelTask.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ModelTask} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ModelTask}
 */
proto.ModelTask.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.StableDiffusionParameter;
      reader.readMessage(value,proto.StableDiffusionParameter.deserializeBinaryFromReader);
      msg.setStablediffusion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ModelTask.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ModelTask.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ModelTask} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ModelTask.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStablediffusion();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.StableDiffusionParameter.serializeBinaryToWriter
    );
  }
};


/**
 * optional StableDiffusionParameter stableDiffusion = 1;
 * @return {?proto.StableDiffusionParameter}
 */
proto.ModelTask.prototype.getStablediffusion = function() {
  return /** @type{?proto.StableDiffusionParameter} */ (
    jspb.Message.getWrapperField(this, proto.StableDiffusionParameter, 1));
};


/**
 * @param {?proto.StableDiffusionParameter|undefined} value
 * @return {!proto.ModelTask} returns this
*/
proto.ModelTask.prototype.setStablediffusion = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ModelTask} returns this
 */
proto.ModelTask.prototype.clearStablediffusion = function() {
  return this.setStablediffusion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ModelTask.prototype.hasStablediffusion = function() {
  return jspb.Message.getField(this, 1) != null;
};


